version: '3'
services:
  redis-server:
    container_name: fantastic-engine-redis
    image: 'redis'
    ports:
      - "6379:6379"
  app:
    container_name: fantastic-engine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis-server
